/* eslint-disable import/no-anonymous-default-export */
// import { QueryClient, QueryClientProvider } from "react-query";
// import { SUBSCRIBE_TO_USER } from "../../user-subscription";
import MovieDetailsPage, { WatchProviders } from "./[id].page";

export default {
  title: "Movies/[id]",
  parameters: {
    nextRouter: {
      path: "/movies/[id]",
      asPath: "/movies/27205",
      query: {
        id: "27205",
      },
    },
    reactQuery: [
      {
        queryKey: ["movie", "details", "27205"],
        data: {
          adult: false,
          backdrop_path: "/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
          belongs_to_collection: null,
          budget: 160000000,
          genres: [
            { id: 28, name: "Action" },
            { id: 878, name: "Science Fiction" },
            { id: 12, name: "Adventure" },
          ],
          homepage: "http://inceptionmovie.warnerbros.com/",
          id: 27205,
          imdb_id: "tt1375666",
          original_language: "en",
          overview:
            "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\", the implantation of another person's idea into a target's subconscious.",
          popularity: 111.593,
          poster_path: "/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
          release_date: "2010-07-15",
          revenue: 825532764,
          runtime: 148,
          spoken_languages: [
            { english_name: "English", iso_639_1: "en", name: "English" },
            { english_name: "Japanese", iso_639_1: "ja", name: "日本語" },
          ],
          status: "Released",
          tagline: "Your mind is the scene of the crime.",
          title: "Inception?",
          video: false,
          vote_average: 8.4,
          vote_count: 30503,
          keywords: {
            keywords: [
              { id: 90, name: "paris, france" },
              { id: 470, name: "spy" },
              { id: 490, name: "philosophy" },
              { id: 1501, name: "allegory" },
              { id: 1566, name: "dream" },
              { id: 1930, name: "kidnapping" },
              { id: 2887, name: "manipulation" },
              { id: 3800, name: "airplane" },
              { id: 4563, name: "virtual reality" },
              { id: 9844, name: "car crash" },
              { id: 10051, name: "heist" },
              { id: 10084, name: "rescue" },
              { id: 10364, name: "mission" },
              { id: 10937, name: "memory" },
              { id: 12436, name: "architecture" },
              { id: 12670, name: "los angeles, california" },
              { id: 186789, name: "dream world" },
              { id: 234868, name: "subconscious" },
            ],
          },
          credits: {
            cast: [
              {
                adult: false,
                gender: 2,
                id: 6193,
                known_for_department: "Acting",
                name: "Leonardo DiCaprio",
                original_name: "Leonardo DiCaprio",
                popularity: 19.212,
                profile_path: "/wo2hJpn04vbtmh0B9utCFdsQhxM.jpg",
                cast_id: 1,
                character: "Dom Cobb",
                credit_id: "52fe4534c3a368484e04de03",
                order: 0,
              },
              {
                adult: false,
                gender: 2,
                id: 24045,
                known_for_department: "Acting",
                name: "Joseph Gordon-Levitt",
                original_name: "Joseph Gordon-Levitt",
                popularity: 6.771,
                profile_path: "/dhv9f3AaozOjpvjAwVzOWlmmT2V.jpg",
                cast_id: 3,
                character: "Arthur",
                credit_id: "52fe4534c3a368484e04de0b",
                order: 1,
              },
              {
                adult: false,
                gender: 2,
                id: 3899,
                known_for_department: "Acting",
                name: "Ken Watanabe",
                original_name: "Ken Watanabe",
                popularity: 4.287,
                profile_path: "/psAXOYp9SBOXvg6AXzARDedNQ9P.jpg",
                cast_id: 2,
                character: "Saito",
                credit_id: "52fe4534c3a368484e04de07",
                order: 2,
              },
              {
                adult: false,
                gender: 2,
                id: 2524,
                known_for_department: "Acting",
                name: "Tom Hardy",
                original_name: "Tom Hardy",
                popularity: 30.288,
                profile_path: "/9bXUMLOBCcnhcUGtfw0pdqbvpiH.jpg",
                cast_id: 7,
                character: "Eames",
                credit_id: "52fe4534c3a368484e04de1b",
                order: 3,
              },
              {
                adult: false,
                gender: 3,
                id: 27578,
                known_for_department: "Acting",
                name: "Elliot Page",
                original_name: "Elliot Page",
                popularity: 10.831,
                profile_path: "/596bLvD4iEz8VGc6TOEhzmPwTMe.jpg",
                cast_id: 5,
                character: "Ariadne",
                credit_id: "52fe4534c3a368484e04de13",
                order: 4,
              },
              {
                adult: false,
                gender: 2,
                id: 95697,
                known_for_department: "Acting",
                name: "Dileep Rao",
                original_name: "Dileep Rao",
                popularity: 1.405,
                profile_path: "/k4OiYIhr886ollgOrvrBs2ZIZbc.jpg",
                cast_id: 19,
                character: "Yusuf",
                credit_id: "52fe4534c3a368484e04de4f",
                order: 5,
              },
              {
                adult: false,
                gender: 2,
                id: 2037,
                known_for_department: "Acting",
                name: "Cillian Murphy",
                original_name: "Cillian Murphy",
                popularity: 14.017,
                profile_path: "/i8dOTC0w6V274ev5iAAvo4Ahhpr.jpg",
                cast_id: 8,
                character: "Robert Fischer, Jr.",
                credit_id: "52fe4534c3a368484e04de1f",
                order: 6,
              },
              {
                adult: false,
                gender: 2,
                id: 13022,
                known_for_department: "Acting",
                name: "Tom Berenger",
                original_name: "Tom Berenger",
                popularity: 9.095,
                profile_path: "/zLxzAdAfu7y02yEx29JSLDgXJZ4.jpg",
                cast_id: 9,
                character: "Peter Browning",
                credit_id: "52fe4534c3a368484e04de23",
                order: 7,
              },
              {
                adult: false,
                gender: 1,
                id: 8293,
                known_for_department: "Acting",
                name: "Marion Cotillard",
                original_name: "Marion Cotillard",
                popularity: 6.932,
                profile_path: "/zChwjQ9D90fxx6cgWz5mUWHNd5b.jpg",
                cast_id: 4,
                character: "Mal Cobb",
                credit_id: "52fe4534c3a368484e04de0f",
                order: 8,
              },
              {
                adult: false,
                gender: 2,
                id: 4935,
                known_for_department: "Acting",
                name: "Pete Postlethwaite",
                original_name: "Pete Postlethwaite",
                popularity: 2.563,
                profile_path: "/2gpa75Ci4y2OKmOc8WXnaeGgyKF.jpg",
                cast_id: 22,
                character: "Maurice Fischer",
                credit_id: "52fe4534c3a368484e04de59",
                order: 9,
              },
              {
                adult: false,
                gender: 2,
                id: 3895,
                known_for_department: "Acting",
                name: "Michael Caine",
                original_name: "Michael Caine",
                popularity: 16.116,
                profile_path: "/hZruclwEPCKw3e83rnFSIH5sRFZ.jpg",
                cast_id: 6,
                character: "Stephen Miles",
                credit_id: "52fe4534c3a368484e04de17",
                order: 10,
              },
              {
                adult: false,
                gender: 2,
                id: 526,
                known_for_department: "Acting",
                name: "Lukas Haas",
                original_name: "Lukas Haas",
                popularity: 2.513,
                profile_path: "/bJ0ZHg5UA9JThkC5wV4Y82T9ucy.jpg",
                cast_id: 10,
                character: "Nash",
                credit_id: "52fe4534c3a368484e04de27",
                order: 11,
              },
              {
                adult: false,
                gender: 1,
                id: 66441,
                known_for_department: "Acting",
                name: "Talulah Riley",
                original_name: "Talulah Riley",
                popularity: 6.348,
                profile_path: "/wIfzSnKvvREEi8lJ6cbuX04HiNG.jpg",
                cast_id: 89,
                character: "Blonde",
                credit_id: "52fe4534c3a368484e04de99",
                order: 12,
              },
              {
                adult: false,
                gender: 2,
                id: 173212,
                known_for_department: "Acting",
                name: "Tohoru Masamune",
                original_name: "Tohoru Masamune",
                popularity: 1.473,
                profile_path: "/7rNjiFzY8KAf4kiZBJK1nBWOz8G.jpg",
                cast_id: 92,
                character: "Japanese Security Guard",
                credit_id: "57d488dec3a3685568007ba1",
                order: 13,
              },
              {
                adult: false,
                gender: 1,
                id: 967376,
                known_for_department: "Acting",
                name: "Taylor Geare",
                original_name: "Taylor Geare",
                popularity: 0.635,
                profile_path: null,
                cast_id: 93,
                character: "Phillipa (5 years)",
                credit_id: "57d488f8c3a368154b0011a1",
                order: 14,
              },
              {
                adult: false,
                gender: 1,
                id: 973135,
                known_for_department: "Acting",
                name: "Claire Geare",
                original_name: "Claire Geare",
                popularity: 0.647,
                profile_path: "/hE8prndXq5IE0RS3IvevTq9iXoN.jpg",
                cast_id: 94,
                character: "Phillipa (3 years)",
                credit_id: "57d48919925141382f0011ca",
                order: 15,
              },
              {
                adult: false,
                gender: 2,
                id: 1677266,
                known_for_department: "Acting",
                name: "Johnathan Geare",
                original_name: "Johnathan Geare",
                popularity: 0.6,
                profile_path: null,
                cast_id: 95,
                character: "James (3 years)",
                credit_id: "57d48aca925141369d00113d",
                order: 16,
              },
              {
                adult: false,
                gender: 2,
                id: 56120,
                known_for_department: "Acting",
                name: "Yuji Okumoto",
                original_name: "Yuji Okumoto",
                popularity: 3.802,
                profile_path: "/eACYrrdj8kZnYMCpUTghbpJ9nVk.jpg",
                cast_id: 96,
                character: "Saito's Attendant",
                credit_id: "57d48b45c3a3680b9f00179e",
                order: 17,
              },
              {
                adult: false,
                gender: 2,
                id: 2246,
                known_for_department: "Acting",
                name: "Earl Cameron",
                original_name: "Earl Cameron",
                popularity: 0.74,
                profile_path: "/jV8eAMdtMZCgwJqmWKdzcl3Wqnm.jpg",
                cast_id: 97,
                character: "Elderly Bald Man",
                credit_id: "57d48b59c3a3685568007cd7",
                order: 18,
              },
              {
                adult: false,
                gender: 2,
                id: 1677267,
                known_for_department: "Acting",
                name: "Ryan Hayward",
                original_name: "Ryan Hayward",
                popularity: 0.6,
                profile_path: null,
                cast_id: 98,
                character: "Lawyer",
                credit_id: "57d48b6dc3a3680ccd001433",
                order: 19,
              },
              {
                adult: false,
                gender: 1,
                id: 1334309,
                known_for_department: "Acting",
                name: "Miranda Nolan",
                original_name: "Miranda Nolan",
                popularity: 1.702,
                profile_path: "/xzQJpQicKgeFtCqZ1xwr0Rhdf5t.jpg",
                cast_id: 99,
                character: "Flight Attendant",
                credit_id: "57d48b84925141382f0012af",
                order: 20,
              },
              {
                adult: false,
                gender: 2,
                id: 535,
                known_for_department: "Acting",
                name: "Russ Fega",
                original_name: "Russ Fega",
                popularity: 0.704,
                profile_path: "/d0W7kq97Ul8Iz5LZIVNDKxSly8M.jpg",
                cast_id: 100,
                character: "Cab Driver",
                credit_id: "57d53da09251415c1e000263",
                order: 21,
              },
              {
                adult: false,
                gender: 2,
                id: 72864,
                known_for_department: "Acting",
                name: "Tim Kelleher",
                original_name: "Tim Kelleher",
                popularity: 1.704,
                profile_path: "/8W3KgoIPUMNjqb3CxC9B8QjBsjM.jpg",
                cast_id: 101,
                character: "Thin Man",
                credit_id: "57d53db4c3a368556800ce41",
                order: 22,
              },
              {
                adult: false,
                gender: 1,
                id: 1677498,
                known_for_department: "Acting",
                name: "Coralie Dedykere",
                original_name: "Coralie Dedykere",
                popularity: 0.6,
                profile_path: null,
                cast_id: 102,
                character: "Bridge Sub Con",
                credit_id: "57d53e46c3a36812b2000308",
                order: 23,
              },
              {
                adult: false,
                gender: 1,
                id: 13695,
                known_for_department: "Acting",
                name: "Silvie Laguna",
                original_name: "Silvie Laguna",
                popularity: 0.805,
                profile_path: "/qDRqkAVWYhUN6P3flH5VuKKVcM8.jpg",
                cast_id: 103,
                character: "Bridge Sub Con",
                credit_id: "57d53ee6c3a3686e3c000cd9",
                order: 24,
              },
              {
                adult: false,
                gender: 2,
                id: 133257,
                known_for_department: "Acting",
                name: "Virgile Bramly",
                original_name: "Virgile Bramly",
                popularity: 1.4,
                profile_path: "/1bbSzSPfT61YV2SI7cgTkbVPMeK.jpg",
                cast_id: 104,
                character: "Bridge Sub Con",
                credit_id: "57d53efcc3a36813230002f5",
                order: 25,
              },
              {
                adult: false,
                gender: 2,
                id: 1677507,
                known_for_department: "Acting",
                name: "Nicolas Clerc",
                original_name: "Nicolas Clerc",
                popularity: 0.6,
                profile_path: null,
                cast_id: 105,
                character: "Bridge Sub Con",
                credit_id: "57d53fde9251415c1e000324",
                order: 26,
              },
              {
                adult: false,
                gender: 2,
                id: 1536351,
                known_for_department: "Acting",
                name: "Jean-Michel Dagory",
                original_name: "Jean-Michel Dagory",
                popularity: 0.706,
                profile_path: null,
                cast_id: 106,
                character: "Bridge Sub Con",
                credit_id: "57d5405f9251415bb300037f",
                order: 27,
              },
              {
                adult: false,
                gender: 2,
                id: 203087,
                known_for_department: "Acting",
                name: "Marc Raducci",
                original_name: "Marc Raducci",
                popularity: 0.98,
                profile_path: null,
                cast_id: 107,
                character: "Lobby Sub Con",
                credit_id: "57d540c7c3a36813230003bc",
                order: 28,
              },
              {
                adult: false,
                gender: 0,
                id: 2157567,
                known_for_department: "Acting",
                name: "Tai-Li Lee",
                original_name: "Tai-Li Lee",
                popularity: 0.6,
                profile_path: null,
                cast_id: 117,
                character: "Tadashi",
                credit_id: "5bcdbc1a0e0a260151022053",
                order: 29,
              },
              {
                adult: false,
                gender: 2,
                id: 2157568,
                known_for_department: "Acting",
                name: "Magnus Nolan",
                original_name: "Magnus Nolan",
                popularity: 0.98,
                profile_path: null,
                cast_id: 118,
                character: "James (20 months)",
                credit_id: "5bcdbc29c3a368286302325d",
                order: 30,
              },
              {
                adult: false,
                gender: 0,
                id: 2157569,
                known_for_department: "Acting",
                name: "Helena Cullinan",
                original_name: "Helena Cullinan",
                popularity: 0.608,
                profile_path: null,
                cast_id: 119,
                character: "Penrose Sub Con",
                credit_id: "5bcdbc36925141613801df6b",
                order: 31,
              },
              {
                adult: false,
                gender: 0,
                id: 1470134,
                known_for_department: "Acting",
                name: "Mark Fleischmann",
                original_name: "Mark Fleischmann",
                popularity: 0.981,
                profile_path: "/4Xki6fvgwjRXVmV9pEinAhqK6XJ.jpg",
                cast_id: 120,
                character: "Penrose Sub Con",
                credit_id: "5bcdbc610e0a26015f0220a3",
                order: 32,
              },
              {
                adult: false,
                gender: 0,
                id: 2157570,
                known_for_department: "Acting",
                name: "Shelley Lang",
                original_name: "Shelley Lang",
                popularity: 0.6,
                profile_path: null,
                cast_id: 121,
                character: "Penrose Sub Con",
                credit_id: "5bcdbc690e0a26016e0219d7",
                order: 33,
              },
              {
                adult: false,
                gender: 2,
                id: 2157571,
                known_for_department: "Acting",
                name: "Adam Cole",
                original_name: "Adam Cole",
                popularity: 0.6,
                profile_path: "/6stnyhAOiA0JuOJ1tTVQKnVvVWj.jpg",
                cast_id: 122,
                character: "Bar Sub Con",
                credit_id: "5bcdbcb2c3a3682870023a6a",
                order: 34,
              },
              {
                adult: false,
                gender: 2,
                id: 1460686,
                known_for_department: "Acting",
                name: "Jack Murray",
                original_name: "Jack Murray",
                popularity: 1.119,
                profile_path: "/kwSd0y9yBTLlHfvmDf5SKh6SX1k.jpg",
                cast_id: 123,
                character: "Bar Sub Con",
                credit_id: "5bcdbcc6c3a368286a024f6a",
                order: 35,
              },
              {
                adult: false,
                gender: 0,
                id: 1742659,
                known_for_department: "Acting",
                name: "Kraig Thornber",
                original_name: "Kraig Thornber",
                popularity: 0.6,
                profile_path: null,
                cast_id: 124,
                character: "Bar Sub Con",
                credit_id: "5bcdbcd1925141613e01de41",
                order: 36,
              },
              {
                adult: false,
                gender: 0,
                id: 2157572,
                known_for_department: "Acting",
                name: "Angela Nathenson",
                original_name: "Angela Nathenson",
                popularity: 0.6,
                profile_path: null,
                cast_id: 125,
                character: "Bar Sub Con",
                credit_id: "5bcdbcda925141612d020ddc",
                order: 37,
              },
              {
                adult: false,
                gender: 1,
                id: 61642,
                known_for_department: "Acting",
                name: "Natasha Beaumont",
                original_name: "Natasha Beaumont",
                popularity: 0.6,
                profile_path: "/svKLagcLLHidlpGpjEnSaYOZxeP.jpg",
                cast_id: 126,
                character: "Bar Sub Con",
                credit_id: "5bcdbce3c3a3682863023393",
                order: 38,
              },
              {
                adult: false,
                gender: 2,
                id: 155308,
                known_for_department: "Acting",
                name: "Carl Gilliard",
                original_name: "Carl Gilliard",
                popularity: 1.4,
                profile_path: null,
                cast_id: 127,
                character: "Lobby Sub Con",
                credit_id: "5bcdbcecc3a368286d02475e",
                order: 39,
              },
              {
                adult: false,
                gender: 1,
                id: 2157573,
                known_for_department: "Acting",
                name: "Jill Maddrell",
                original_name: "Jill Maddrell",
                popularity: 0.6,
                profile_path: null,
                cast_id: 128,
                character: "Lobby Sub Con",
                credit_id: "5bcdbcf5925141613401f960",
                order: 40,
              },
              {
                adult: false,
                gender: 1,
                id: 565500,
                known_for_department: "Acting",
                name: "Alex Lombard",
                original_name: "Alex Lombard",
                popularity: 0.649,
                profile_path: "/7rRd2byURAqE2QObL3wJyHYQbpL.jpg",
                cast_id: 129,
                character: "Lobby Sub Con",
                credit_id: "5bcdbd26c3a368286a025014",
                order: 41,
              },
              {
                adult: false,
                gender: 1,
                id: 98811,
                known_for_department: "Acting",
                name: "Nicole Pulliam",
                original_name: "Nicole Pulliam",
                popularity: 1.553,
                profile_path: "/XcJAw0P7bPE9ET52P4fZ2hdokk.jpg",
                cast_id: 130,
                character: "Lobby Sub Con",
                credit_id: "5bcdbd2f925141612a01f459",
                order: 42,
              },
              {
                adult: false,
                gender: 2,
                id: 1168075,
                known_for_department: "Acting",
                name: "Peter Basham",
                original_name: "Peter Basham",
                popularity: 0.784,
                profile_path: "/4AtYLZu7jX5ROgB9rCzYhicbLqk.jpg",
                cast_id: 131,
                character: "Fischer's Jet Captain",
                credit_id: "5bcdbd38925141612d020fa2",
                order: 43,
              },
              {
                adult: false,
                gender: 2,
                id: 33241,
                known_for_department: "Acting",
                name: "Michael Gaston",
                original_name: "Michael Gaston",
                popularity: 3.232,
                profile_path: "/ohdf9vJz8IuEY6o53IsRiVOstK0.jpg",
                cast_id: 132,
                character: "Immigration Officer",
                credit_id: "5bcdbd41c3a3682873021710",
                order: 44,
              },
              {
                adult: false,
                gender: 2,
                id: 208492,
                known_for_department: "Acting",
                name: "Felix Scott",
                original_name: "Felix Scott",
                popularity: 0.716,
                profile_path: "/sRlcbtzrmVMEVdJAH6xocbYdfhr.jpg",
                cast_id: 133,
                character: "Businessman",
                credit_id: "5bcdbd4a925141612601fbd1",
                order: 45,
              },
              {
                adult: false,
                gender: 2,
                id: 17291,
                known_for_department: "Acting",
                name: "Andrew Pleavin",
                original_name: "Andrew Pleavin",
                popularity: 0.6,
                profile_path: "/vFYWQCmk1yipKAjUr9J3mBdHKNZ.jpg",
                cast_id: 134,
                character: "Businessman",
                credit_id: "5bcdbd57925141613b01ee04",
                order: 46,
              },
              {
                adult: false,
                gender: 0,
                id: 2011839,
                known_for_department: "Acting",
                name: "Lisa Reynolds",
                original_name: "Lisa Reynolds",
                popularity: 0.98,
                profile_path: "/kBFTzvYveef33Ci4PlKuDe7wGuD.jpg",
                cast_id: 135,
                character: "Private Nurse",
                credit_id: "5bcdbd6c0e0a26016b022cba",
                order: 47,
              },
              {
                adult: false,
                gender: 0,
                id: 2157574,
                known_for_department: "Acting",
                name: "Jason Tendell",
                original_name: "Jason Tendell",
                popularity: 0.6,
                profile_path: null,
                cast_id: 136,
                character: "Fischer's Driver",
                credit_id: "5bcdbd770e0a260162022691",
                order: 48,
              },
              {
                adult: false,
                gender: 0,
                id: 2157575,
                known_for_department: "Acting",
                name: "Jack Gilroy",
                original_name: "Jack Gilroy",
                popularity: 0.6,
                profile_path: null,
                cast_id: 137,
                character: "Old Cobb",
                credit_id: "5bcdbd84925141612d020ffc",
                order: 49,
              },
              {
                adult: false,
                gender: 1,
                id: 1217812,
                known_for_department: "Acting",
                name: "Shannon Welles",
                original_name: "Shannon Welles",
                popularity: 1.38,
                profile_path: null,
                cast_id: 138,
                character: "Old Mal",
                credit_id: "5bcdbd93c3a368286302346f",
                order: 50,
              },
            ],
          },
          "watch/providers": {
            results: {
              US: {
                link: "https://www.themoviedb.org/movie/27205-inception/watch?locale=US",
                rent: [
                  {
                    display_priority: 2,
                    logo_path: "/q6tl6Ib6X5FT80RMlcDbexIo4St.jpg",
                    provider_id: 2,
                    provider_name: "Apple iTunes",
                  },
                  {
                    display_priority: 3,
                    logo_path: "/p3Z12gKq2qvJaUOMeKNU2mzKVI9.jpg",
                    provider_id: 3,
                    provider_name: "Google Play Movies",
                  },
                  {
                    display_priority: 11,
                    logo_path: "/sVBEF7q7LqjHAWSnKwDbzmr2EMY.jpg",
                    provider_id: 10,
                    provider_name: "Amazon Video",
                  },
                  {
                    display_priority: 13,
                    logo_path: "/vDCcryHD32b0yMeSCgBhuYavsmx.jpg",
                    provider_id: 192,
                    provider_name: "YouTube",
                  },
                  {
                    display_priority: 36,
                    logo_path: "/hBdCQamqj7J2VPZNbqf0wiLBous.jpg",
                    provider_id: 7,
                    provider_name: "Vudu",
                  },
                  {
                    display_priority: 47,
                    logo_path: "/paq2o2dIfQnxcERsVoq7Ys8KYz8.jpg",
                    provider_id: 68,
                    provider_name: "Microsoft Store",
                  },
                  {
                    display_priority: 49,
                    logo_path: "/nSr2IQSwc5C2QrttIWen8s06ofe.jpg",
                    provider_id: 279,
                    provider_name: "Redbox",
                  },
                  {
                    display_priority: 53,
                    logo_path: "/qZdEeINwQotbr1Rq15dL5G2BaAh.jpg",
                    provider_id: 358,
                    provider_name: "DIRECTV",
                  },
                  {
                    display_priority: 133,
                    logo_path: "/p1e92kLeYHalxC9GClqNJ75lBDG.jpg",
                    provider_id: 352,
                    provider_name: "AMC on Demand",
                  },
                  {
                    display_priority: 167,
                    logo_path: "/xiUQmGI2bi8Rn6C5u2bArB4YHMp.jpg",
                    provider_id: 486,
                    provider_name: "Spectrum On Demand",
                  },
                ],
                flatrate: [
                  {
                    display_priority: 6,
                    logo_path: "/giwM8XX4V2AQb9vsoN7yti82tKK.jpg",
                    provider_id: 15,
                    provider_name: "Hulu",
                  },
                  {
                    display_priority: 8,
                    logo_path: "/aS2zvJWn9mwiCOeaaCkIh4wleZS.jpg",
                    provider_id: 384,
                    provider_name: "HBO Max",
                  },
                ],
                buy: [
                  {
                    display_priority: 2,
                    logo_path: "/q6tl6Ib6X5FT80RMlcDbexIo4St.jpg",
                    provider_id: 2,
                    provider_name: "Apple iTunes",
                  },
                  {
                    display_priority: 3,
                    logo_path: "/p3Z12gKq2qvJaUOMeKNU2mzKVI9.jpg",
                    provider_id: 3,
                    provider_name: "Google Play Movies",
                  },
                  {
                    display_priority: 11,
                    logo_path: "/sVBEF7q7LqjHAWSnKwDbzmr2EMY.jpg",
                    provider_id: 10,
                    provider_name: "Amazon Video",
                  },
                  {
                    display_priority: 13,
                    logo_path: "/vDCcryHD32b0yMeSCgBhuYavsmx.jpg",
                    provider_id: 192,
                    provider_name: "YouTube",
                  },
                  {
                    display_priority: 36,
                    logo_path: "/hBdCQamqj7J2VPZNbqf0wiLBous.jpg",
                    provider_id: 7,
                    provider_name: "Vudu",
                  },
                  {
                    display_priority: 47,
                    logo_path: "/paq2o2dIfQnxcERsVoq7Ys8KYz8.jpg",
                    provider_id: 68,
                    provider_name: "Microsoft Store",
                  },
                  {
                    display_priority: 49,
                    logo_path: "/nSr2IQSwc5C2QrttIWen8s06ofe.jpg",
                    provider_id: 279,
                    provider_name: "Redbox",
                  },
                  {
                    display_priority: 53,
                    logo_path: "/qZdEeINwQotbr1Rq15dL5G2BaAh.jpg",
                    provider_id: 358,
                    provider_name: "DIRECTV",
                  },
                  {
                    display_priority: 133,
                    logo_path: "/p1e92kLeYHalxC9GClqNJ75lBDG.jpg",
                    provider_id: 352,
                    provider_name: "AMC on Demand",
                  },
                ],
              },
            },
          },
        },
      },
    ],
  },
};

export const WatchProvidersComponent = () => {
  return <WatchProviders movieId={27205} />;
};

export const Foo = () => {
  return <div>Foo</div>;
};

export const Page = () => {
  return <MovieDetailsPage />;
};

Page.story = {
  parameters: {
    // nextRouter: {
    //   path: "/movies/[id]",
    //   asPath: "/movies/27205",
    //   query: {
    //     id: "27205",
    //   },
    // },
  },
};
